# Site settings
title: FNA
description: FNA is a reimplementation of the Microsoft XNA Game Studio 4.0 Refresh libraries.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fna-xna.github.io" # the base hostname & protocol for your site
permalink: /articles/:title

# Build settings
markdown: kramdown
